[amharic] Update links for Gurage/Sebatbeit Blin and Geez keyboards
keymanapp/keyman.com pull request #193
Opened 2020-10-29 21:12 UTC by LornaSIL

These changes were made at the request of @dyacob.

2020-10-29 22:56 UTC, mcdurdin requested changes
A few malformed links to fix but apart from that looks good.

2020-10-29 22:56 UTC, mcdurdin commented on amharic/index.php
> +      <li><a href="/keyboards/https://keyman.com/keyboards/gff_geez">Ge'ez</a></li>
```suggestion
      <li><a href="/keyboards/gff_geez">Ge'ez</a></li>
```

2020-10-29 22:56 UTC, mcdurdin commented on tigrigna/eritrean.php
> +        <li><a href="/keyboards/https://keyman.com/keyboards/gff_geez">Ge'ez</a></li>
```suggestion
        <li><a href="/keyboards/gff_geez">Ge'ez</a></li>
```

2020-10-29 22:56 UTC, mcdurdin commented on tigrigna/index.php
> +        <li><a href="/keyboards/https://keyman.com/keyboards/gff_geez">Ge'ez</a></li>
```suggestion
        <li><a href="/keyboards/gff_geez">Ge'ez</a></li>
```

2020-10-30 02:36 UTC, darcywong00 approved these changes
lgtm

2020-10-30 03:33 UTC, mcdurdin approved these changes

2020-10-30 03:33 UTC, merged