feat: Localize keyboards index page 📡
keymanapp/keyman.com pull request #521
Opened 2024-12-11 06:57 UTC by darcywong00

Re-implements #500 for #384

This updates Locale.php for localizing the keyboards/ index page

## Changes

### Locale.php
* Validate the new locale before overriding the current locale
* `setTextDomain()` to manage the localization files
* Add `_s()` wrapper

### keyboards/index.php
* Use the pattern described in #384 of storing the localized strings into an array

## Screenshots
 
**French**

http://keyman.com.localhost/keyboards/?lang=fr-FR

![image](https://github.com/user-attachments/assets/36e067d7-d68b-4aac-971c-f51883120092)

**Spanish**

http://keyman.com.localhost/keyboards/?lang=es-ES

![image](https://github.com/user-attachments/assets/73944611-d263-411f-9f4f-b973bd37d76a)

2024-12-12 01:20 UTC, darcywong00 commented on _includes/locale/Locale.php
> +    }
Refactored from #500 to Locale.php.
This way, pages don't need to make all the calls to `bindtextdomain()` and `setTextDomain()`

2025-01-17 00:56 UTC, mcdurdin requested changes

2025-01-17 00:56 UTC, mcdurdin commented on _includes/locale/en/LC_MESSAGES/keyboards-en.po
> +msgid "Keyboard search%s"
Anywhere we have parameters we need to index them. Particularly important if there are multiple parameters in a string.

```suggestion
msgid "Keyboard search%1$s"
```

2025-01-17 00:56 UTC, mcdurdin commented on _includes/locale/en/LC_MESSAGES/keyboards-en.po
> +msgstr "Keyboard search%s"
```suggestion
msgstr "Keyboard search%1$s"
```

2025-01-17 00:56 UTC, mcdurdin commented on _includes/locale/en/LC_MESSAGES/keyboards-en.po
> +msgstr "Enter the name of a keyboard or language to search for%s"
```suggestion
msgid "Enter the name of a keyboard or language to search for%1$s"
msgstr "Enter the name of a keyboard or language to search for%1$s"
```

2025-01-17 00:56 UTC, mcdurdin commented on _includes/locale/en/LC_MESSAGES/keyboards-en.po
> +msgstr "%scountries%s to filter your search results. For example"
```suggestion
# (keyboards)
msgid "%1$skeyboards%2$s"
msgstr "%1$skeyboards%2$s"

# (languages)
msgid "%1$slanguages%2$s"
msgstr "%1$slanguages%2$s"

# (scripts, writing systems) or...
msgid "%1$sscripts, writing systems%2$s or"
msgstr "%1$sscripts, writing systems%2$s or"

# (countries) to filter your search results...
msgid "%1$scountries%2$s to filter your search results. For example"
msgstr "%1$scountries%2$s to filter your search results. For example"
```

2025-01-17 00:56 UTC, mcdurdin commented on _includes/locale/en/LC_MESSAGES/keyboards-en.po
> +msgstr "searches for Tigrigna %sEthiopia%s"
```suggestion
msgid "searches for Tigrigna %1$sEthiopia%2$s"
msgstr "searches for Tigrigna %1$sEthiopia%2$s"
```

2025-01-17 00:56 UTC, mcdurdin commented on _includes/locale/en/LC_MESSAGES/keyboards-es-ES.po
> +msgstr "%stescados%s"
ditto for this file

2025-01-17 00:56 UTC, mcdurdin commented on _includes/locale/en/LC_MESSAGES/keyboards-fr-FR.po
> +
ditto

2025-01-17 00:56 UTC, mcdurdin commented on keyboards/index.php
> +  $keyboardIndexStrings = Locale::localize('keyboards', [
This all feels very fragile -- arrays across multiple files which have to match up. A lot of duplication of these strings -- 6 times:
* twice in keyboards-en.po
* once each in keyboards-es-ES.po, keyboards-fr-FR.po
* twice in keyboards/index.php -- here and where referenced.

This will need automatic validation to keep in sync or it's going to get very hard to maintain. (Why do we need the array defined here as well as in the keyboards-en.po file? Can't we just use the list in that file as our starting point?)

It may be better to use an identifier which is not the whole string? e.g. I see we have also 'keyboard search' 'keyman keyboard search' 'keyboard search%s', 'search', 'new search' ... lots of repetition here and risk of confusion!

2025-01-17 00:56 UTC, mcdurdin commented on keyboards/index.php
> +      <label for="search-q"><?= Locale::_s($keyboardIndexStrings['Keyboard search%s'], ":") ?></label><input id="search-q" type="text" placeholder="<?= $keyboardIndexStrings['Enter language or keyboa
Why have you split the `:` out from the string? Here and other places? Seems to make the strings much more complicated than they need to be

2025-01-17 00:56 UTC, mcdurdin commented on keyboards/index.php
> +  $keyboardIndexStrings = Locale::localize('keyboards', [
It might be sensible to establish a convention for a shorthand reference e.g. `$_` rather than a long name like `$keyboardIndexStrings`

2025-01-20 01:40 UTC, darcywong00 commented on keyboards/index.php
> +      <label for="search-q"><?= Locale::_s($keyboardIndexStrings['Keyboard search%s'], ":") ?></label><input id="search-q" type="text" placeholder="<?= $keyboardIndexStrings['Enter language or keyboa
ok, I've consolidated punctuation back into the strings in edd7430134e7881bd1a532ee3fbe321bdf58e908

2025-01-20 03:41 UTC, darcywong00 commented on keyboards/index.php
> +  $keyboardIndexStrings = Locale::localize('keyboards', [
Based on :duck: -
* Replaced $keyboardIndexStrings array with `_()` alias
* Updated `Locale::localize()` so it doesn't restore textdomain

2025-01-20 03:58 UTC, mcdurdin approved these changes
This looks a lot easier to maintain. Good work!

2025-01-20 04:03 UTC, merged